"""Generate reproducible Python code for json2ciw process models."""

from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent


@dataclass(frozen=True)
class ScriptConfig:
    """Configure a generated simulation experiment runner.

    Parameters
    ----------
    num_reps : int, optional
        Number of independent simulation replications, by default 50.
    runtime : float, optional
        Total simulation time horizon for each replication, by default
        1000.0. Results are measured after ``warmup``.
    warmup : float, optional
        Initial time period to exclude from result measures, by default 0.0.
    n_jobs : int, optional
        Number of joblib workers supplied to ``multiple_replications``.
        The default of 1 prioritises transparent, portable execution of the
        generated script. Set to -1 to use all available workers.
    output_directory : str, optional
        Directory, relative to the working directory, in which CSV outputs
        are written, by default ``"results"``.
    output_stem : str, optional
        Prefix used for generated result filenames, by default
        ``"simulation"``.
    """

    num_reps: int = 5
    runtime: float = 1000.0
    warmup: float = 0.0
    n_jobs: int = 1
    output_directory: str = "results"
    output_stem: str = "simulation"

    def __post_init__(self) -> None:
        if self.num_reps < 1:
            raise ValueError("num_reps must be at least 1.")
        if self.runtime <= 0:
            raise ValueError("runtime must be greater than 0.")
        if self.warmup < 0:
            raise ValueError("warmup must be non-negative.")
        if self.warmup >= self.runtime:
            raise ValueError("warmup must be smaller than runtime.")
        if self.n_jobs == 0:
            raise ValueError("n_jobs must not be zero.")
        if not self.output_directory:
            raise ValueError("output_directory must not be empty.")
        if not self.output_stem:
            raise ValueError("output_stem must not be empty.")


def render_script(
    model_filename: str | Path,
    config: ScriptConfig | None = None,
) -> str:
    """Render a standalone reproducible json2ciw experiment runner.

    Parameters
    ----------
    model_filename : str or pathlib.Path
        Filename or relative path of the JSON model file that will accompany
        the generated script. Absolute paths are rejected to keep generated
        runners portable.
    config : ScriptConfig or None, optional
        Replication and output configuration. The default is ``ScriptConfig()``.

    Returns
    -------
    str
        Complete UTF-8 Python source for the experiment runner.

    Raises
    ------
    ValueError
        If ``model_filename`` is absolute or empty.
    """
    config = config or ScriptConfig()
    model_path = Path(model_filename)

    if model_path.is_absolute():
        raise ValueError("model_filename must be relative to the generated script.")
    if not str(model_path) or str(model_path) == ".":
        raise ValueError("model_filename must name a JSON model file.")

    return dedent(
        f'''\
        """Reproducible Ciw simulation experiment generated by json2ciw.

        Model file: {model_path.as_posix()}

        """

        from pathlib import Path
        from pprint import pprint

        import ciw

        from json2ciw.datasets import load_model_file
        from json2ciw.engine import CiwConverter, multiple_replications
        from json2ciw.results import summarise_results, summarise_results_by_class
        from json2ciw.schema import ProcessModel


        MODEL_PATH = Path(__file__).parent / {model_path.as_posix()!r}

        N_REPS = {config.num_reps!r}
        RUNTIME = {config.runtime!r}
        WARMUP = {config.warmup!r}
        N_JOBS = {config.n_jobs!r}

        OUTPUT_DIRECTORY = Path({config.output_directory!r})
        OUTPUT_STEM = {config.output_stem!r}


        def main() -> None:
            # Load the JSON specification and validate its activities,
            # distributions, customer classes, and routing probabilities.
            model_data = load_model_file(MODEL_PATH)
            model = ProcessModel(**model_data)

            # Convert the validated process model to the keyword arguments
            # accepted by ciw.create_network(). This handles both ordinary
            # list-based and customer-class-keyed Ciw inputs.
            converter = CiwConverter(model)
            params = converter.generate_params()

            # To inspect the concrete Ciw inputs derived from the JSON model,
            # uncomment the following two lines before network creation.
            # print("\\nCiw network parameters:")
            # pprint(params)

            network = ciw.create_network(**params)

            df_reps = multiple_replications(
                network=network,
                process_model=model,
                num_reps=N_REPS,
                runtime=RUNTIME,
                warmup=WARMUP,
                n_jobs=N_JOBS,
            )

            overall_summary = summarise_results(df_reps)

            print(f"\\nModel: {{model.name}}")
            print("Overall results")
            print(overall_summary.to_string(index=False))

            class_summary = None
            if model.customer_classes:
                class_label_map = {{
                    customer_class.name: (
                        customer_class.label or customer_class.name
                    )
                    for customer_class in model.customer_classes
                }}
                class_summary = summarise_results_by_class(
                    df_reps,
                    class_label_map=class_label_map,
                )
                print("\\nResults by customer class")
                print(class_summary.to_string(index=False))

            OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
            df_reps.to_csv(
                OUTPUT_DIRECTORY / f"{{OUTPUT_STEM}}_replications.csv",
                index=False,
            )
            overall_summary.to_csv(
                OUTPUT_DIRECTORY / f"{{OUTPUT_STEM}}_overall_summary.csv",
                index=False,
            )
            if class_summary is not None:
                class_summary.to_csv(
                    OUTPUT_DIRECTORY / f"{{OUTPUT_STEM}}_class_summary.csv",
                    index=False,
                )

            print(f"\\nSaved results to: {{OUTPUT_DIRECTORY.resolve()}}")


        if __name__ == "__main__":
            main()
        '''
    )


def write_script(
    output_path: str | Path,
    model_filename: str | Path,
    config: ScriptConfig | None = None,
) -> Path:
    """Write a reproducible experiment runner to a Python file.

    Parameters
    ----------
    output_path : str or pathlib.Path
        Destination Python filename.
    model_filename : str or pathlib.Path
        JSON model path, relative to the destination script's directory.
    config : ScriptConfig or None, optional
        Replication and output configuration. The default is ``ScriptConfig()``.

    Returns
    -------
    pathlib.Path
        The written output path.
    """
    output_path = Path(output_path)
    output_path.write_text(
        render_script(model_filename=model_filename, config=config),
        encoding="utf-8",
    )
    return output_path