name: json2ciw
channels:
  - conda-forge
dependencies:
  - hatch
  - joblib=1.5.3
  - matplotlib=3.10.8
  - numpy=2.4.0
  - pandas=2.3.3
  - pip=25.3
  - plotly=6.6.0
  - pydantic=2.12.5
  - pytest=9.0.2
  - python=3.12
  - rich=14.3.3
  - ruff
  - streamlit=1.55.0
  - pip:
    - ciw==3.2.7
    - great-docs==0.14.0
    - -e .
