name: Check Alt Text
run-name: Check Alt Text

on:
  push:
    paths:
      - '**.qmd'
      - '.github/workflows/alt-text.yml'
  pull_request:
    paths:
      - '**.qmd'
      - '.github/workflows/alt-text.yml'
  workflow_dispatch:

jobs:
  check-alt-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lintquarto/alt-text-linter@main
